// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbVKG_Scb_m7cVyDqvIhTe8FKCfWK7iEY',
    appId: '1:1093150853537:web:21eb81b78b8b251c7923e0',
    messagingSenderId: '1093150853537',
    projectId: 'test2-adbee',
    authDomain: 'test2-adbee.firebaseapp.com',
    storageBucket: 'test2-adbee.firebasestorage.app',
    measurementId: 'G-YQPFPVJ5TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD-ZHgHs7ajyBhl9k1abmYKwAge9zNE3w',
    appId: '1:1093150853537:android:c6b98374402a48107923e0',
    messagingSenderId: '1093150853537',
    projectId: 'test2-adbee',
    storageBucket: 'test2-adbee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg5acRCELBTVFBU6d9W05uCixadLBWFgE',
    appId: '1:1093150853537:ios:20ae3197b417413f7923e0',
    messagingSenderId: '1093150853537',
    projectId: 'test2-adbee',
    storageBucket: 'test2-adbee.firebasestorage.app',
    iosBundleId: 'com.example.juniorAppFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg5acRCELBTVFBU6d9W05uCixadLBWFgE',
    appId: '1:1093150853537:ios:20ae3197b417413f7923e0',
    messagingSenderId: '1093150853537',
    projectId: 'test2-adbee',
    storageBucket: 'test2-adbee.firebasestorage.app',
    iosBundleId: 'com.example.juniorAppFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbVKG_Scb_m7cVyDqvIhTe8FKCfWK7iEY',
    appId: '1:1093150853537:web:94afbecb1248fc647923e0',
    messagingSenderId: '1093150853537',
    projectId: 'test2-adbee',
    authDomain: 'test2-adbee.firebaseapp.com',
    storageBucket: 'test2-adbee.firebasestorage.app',
    measurementId: 'G-SC90QKBRG9',
  );
}
